name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install test dependencies
      run: |
        pip install pytest pytest-cov nbconvert
    
    - name: Test notebook execution
      run: |
        # Convert notebook to Python script and check syntax
        jupyter nbconvert --to script protein_graph_builder.ipynb
        python -m py_compile protein_graph_builder.py
    
    - name: Check code quality
      run: |
        pip install flake8
        # Run flake8 on example scripts
        flake8 examples/ --max-line-length=100 --ignore=E501,W503 || true
    
    - name: Test example scripts
      run: |
        # Syntax check only (no actual data required)
        python -m py_compile examples/load_graphs.py

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install linting tools
      run: |
        pip install black flake8 mypy
    
    - name: Check code formatting with black
      run: |
        black --check examples/ --line-length=100 || true
    
    - name: Run flake8
      run: |
        flake8 examples/ --max-line-length=100 --ignore=E501,W503 || true
    
    - name: Run mypy
      run: |
        mypy examples/ --ignore-missing-imports || true

  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check documentation
      run: |
        # Verify all required documentation files exist
        test -f README.md
        test -f QUICK_START.md
        test -f CONTRIBUTING.md
        test -f CHANGELOG.md
        test -f LICENSE
        echo "✓ All documentation files present"
    
    - name: Check links in README
      run: |
        # Install markdown link checker
        npm install -g markdown-link-check || true
        # Check links (allow failure as some links may be private)
        markdown-link-check README.md --quiet || true
